### PR TITLE
Remove vertical line on My Library Page

### PR DESCRIPTION
**Pull request by akayjoshi**
## Description
There is a vertical line between My Collections and Available Collections that is looking confusing so the vertical line is removed.

## Phabricator Ticket
https://phabricator.wikimedia.org/T289255

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

### CODE REVIEW

**Comment by akayjoshi** [comment]
vertical-line-removed

**Comment by akayjoshi** [comment]
Sorry, I forget to add a feature in this PR. I will push a commit soon.

**Comment by akayjoshi** [comment]
Hello there, I have pushed the remaining commit, now the PR can be merge.

**Review by suecarmol — CHANGES_REQUESTED** [review]
Thank you for working on this!

There are a couple of things I think will also help shorten the underline.

```suggest
.collection-tab-item.active{
    color: #000000;
    box-shadow: inset 10px 0px 0 white, inset 0 -3px 0 #000000;
}

.collection-tab-item:hover{
    font-family: Roboto;
    color: #000000;
    box-shadow: inset 10px 0px 0 white, inset 0 -3px 0 #565656;
}

```

**Comment by akayjoshi** [comment]
Hello suecarmol, I made the required changes, thank you.

**Review by suecarmol — APPROVED** [review]
Thank you for contributing to The Wikipedia Library and for your work on this!

**Comment by akayjoshi** [comment]
Thank you @suecarmol for your support.

**Pull request merged**
