### PR TITLE
If an authorization is to an EMAIL, CODES, or LINK authorization method partner, the Renew/Extend button should always be accessible

### PR DESCRIPTION
**Pull request by suecarmol**
## Description
Changed the behavior of the `apply` and `has_auths` flags so that the Apply button is enabled for partners with certain authorization methods.

Fixed the resource tile partial view to show the `Renew`, `Extend` or `View application` buttons on individual access resources.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)
Before, it was impossible to ask for renewal if the editor already had authorization (even if It had already expired).

## Phabricator Ticket
[//]: # (Link to the Phabricator ticket)
[T271088](https://phabricator.wikimedia.org/T271088)
[T270649](https://phabricator.wikimedia.org/T270649)

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)
1. Create an authorization from a partner with  EMAIL, CODES, or LINK authorization method.
2. Create another authorization from a partner with  EMAIL, CODES, or LINK authorization method.
3. Create one pending application for one of the two partners.
4. Check that the `Apply` button for the partner with the pending application is disabled.
5. Check that the `Apply` button for the partner without the pending application is enabled.

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)
**Partner with Authorization Method EMAIL that has no open applications**
Screen Shot 2021-03-12 at 21 36 39

**Partner with Authorization Method EMAIL that has an open application**
Screen Shot 2021-03-12 at 21 36 55

**My Library view with the Extend and View Application buttons showing**
Screen Shot 2021-03-15 at 19 55 07

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Samwalton9** [comment]
This seems like a sensible improvement. Per the second sentence in https://phabricator.wikimedia.org/T271088, though, does this change any behaviour on My Library?

**Comment by suecarmol** [comment]
> This seems like a sensible improvement. Per the second paragraph in https://phabricator.wikimedia.org/T271088, though, does this change any behaviour on My Library?

It doesn't. I am working on implementing that in `My Library`. It seems we have a bug there because I am seeing that the Authorization object is trying to get `latest_sent_app` and `open_app` attributes that don't exist. The `Authorization` model has a `get_latest_sent_app` method and a `get_latest_app` method. @jsnshrmn did these attributes exist before?

**Comment by suecarmol** [comment]
@Samwalton9 I think I have figured out why the buttons weren't showing. Let me know if I missed something.

**Comment by Samwalton9** [comment]
That looks like a much-needed refactoring of the open app code.

If I recall correctly, Jason had reworked some of the `latest_sent_app` and similar methods at some point, he might have missed updating the calls in My Library.

**Review by jsnshrmn — APPROVED** [review]
Yeah, I'm not sure how we got here, but it seems like a clear oversight to me. This looks great. Thanks for your work on this!

**Pull request merged**
