### PR TITLE
Fixed T240598: Send content of comments in emails

### PR DESCRIPTION
**Pull request by soumyaa1804**
[T240598](https://phabricator.wikimedia.org/T240598)

### CODE REVIEW

**Comment by Samwalton9** [comment]
Looks like the build is running correctly except for formatting - can you run `docker exec CONTAINER /venv/bin/black -t py37 /app/TWLight` and commit the result? It will just reformat the code a little :)

**Comment by soumyaa1804** [comment]
image
I ran that command but it is still showing an error

**Comment by Samwalton9** [comment]
It looks like the `test_under_discussion_signal` test is failing: https://github.com/WikipediaLibrary/TWLight/blob/75525c078f83edf78aec67ad2c417f14b0ab4f47/TWLight/applications/tests.py#L2762

Seems to be because we don't create an Editor to attach to the User object used in that test (`request.user = UserFactory()`). I think we should be able to fix this by adding an editor to the user (`editor = EditorFactory(user=request.user)`) on the line below in that test :)

**Comment by soumyaa1804** [comment]
Is it because we didn't check the condition for username and directly used `user.editor.wp_username` like:
```
 if hasattr(user, "editor"):
                username = user.editor.wp_username
            else:
                username = user.username
```

**Comment by Samwalton9** [comment]
That could be a solution, though in production users should always have attached editors, so we shouldn't ever need to use `user.username`. 

I think I've realised why this is though, we send the comment from the coordinator, not from `request.user`. I think `editor = EditorFactory(user=self.coordinator)` should fix things.

**Comment by soumyaa1804** [comment]
Though the test cases passed, when I am trying to view details of any user through admin site, I am getting this error
image

**Comment by soumyaa1804** [comment]
Also when I tried to log in again through Oauth, it gave this error:
image

**Comment by Samwalton9** [comment]
It looks like maybe you haven't run migrations since some recent code updates, do `docker-compose exec twlight /app/bin/virtualenv_migrate.sh`

**Comment by soumyaa1804** [comment]
Ya, my bad! I pulled the code from upstream but didn't push to origin. sorry
It's working now. Thanks

**Comment by Samwalton9** [comment]
Look good! Thanks again for your contributions! :)

**Comment by soumyaa1804** [comment]
Thanks to you for patiently addressing me and elaborating the issue whenever needed. Got to learn a lot about Django_comments through this issue. :)

**Comment by Samwalton9** [comment]
No problem!

I saw you assigned yourself to https://phabricator.wikimedia.org/T226648, is that what you're planning to work on next? :)

**Comment by soumyaa1804** [comment]
Yes 🙈! I'll start working on it from monday.

**Pull request merged**
