### PR TITLE
In /admin default language is selected to english on resource pages

### PR DESCRIPTION
**Pull request by YashAgrawal9265**
[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
In the admin interface, on resource pages, staff can select the language of fields they want to edit. 90% of the time we want to edit the English versions, so I have added English language as selected in the drop down by default.

**Before Change:**

**After Change:** 

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

## Phabricator Ticket
https://phabricator.wikimedia.org/T240170

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Samwalton9** [comment]
Can I just confirm that when you open, for example, `/admin/resources/partner/1/change/`, the language selector at the top of the page defaults to English? That's not clear from the screenshots.

**Comment by YashAgrawal9265** [comment]
I have checked, it is showing English by default..



and when we click on **+** button then also it is showing English language by default.

**Comment by Samwalton9** [comment]
Hi Yash,

Unfortunately this isn't quite what I had in mind with this ticket. When browsing a resource, there is a language selector at the top of the page:

Screenshot 2020-11-16 at 11 08 16

It's this selector (which is `ar` by default) which we want to default to English.

**Comment by YashAgrawal9265** [comment]
Hi Sam,
I got it.
So I have to make it default as **en** or **en-gb**

**Comment by YashAgrawal9265** [comment]
Hi Sam,
I got it.
So tell me that now I have to make it default as **en** or **en-gb** ?

**Comment by Samwalton9** [comment]
`en` :)

**Comment by YashAgrawal9265** [comment]
Hi Sam,
I am unable to find the **Add Partner** in **Partner models.** Can you help me?

2020-11-16 (1)_LI

**Comment by YashAgrawal9265** [comment]
Hi Sam, 
Can you help me that, how I can access the language field which is beside of Add Partner, which I have marked in above image

**Comment by Samwalton9** [comment]
@YashAgrawal9265 This isn't a model field, rather it's a capability added by the `Modeltranslation` application (https://django-modeltranslation.readthedocs.io/en/latest/).

I _think_ this is the information you need on how to change the default, but I could be wrong: https://django-modeltranslation.readthedocs.io/en/latest/installation.html?highlight=default#modeltranslation-default-language

**Comment by YashAgrawal9265** [comment]
@Samwalton9
 


In settings.py the default language is already selected to the **en** by default.
According to me for solving this issue, changes should be done in **translation.py** file. I have tried some changes, but they are giving errors.
Can You help me out that what changes should I do in **translation.py** to solve the issue?

**Comment by Samwalton9** [comment]
Hey Yash - I'm not sure how to proceed with this, it's clearly not something we can change easily in a configuration variable. I'd suggest you work on other tasks because this is a very low priority task for us and we don't have much bandwidth to provide help :)

**Comment by suecarmol** [comment]
Since this task is a low priority and the team is focusing on other work, I am going to close this PR. Once we have more bandwidth to take a look at this, we can re-open this PR (or even create a new one).

**Pull request closed without merging**
