### PR TITLE
Hide applications to bundle partners

### PR DESCRIPTION
**Pull request by illseption**
Made changes to /TWLight/users/views.py, as given in T242740

### CODE REVIEW

**Comment by soumyaa1804** [comment]
Looks like the build is running correctly except for formatting - can you run `docker-compose exec twlight /venv/bin/black -t py37 /app/TWLight` and commit the result? It will just reformat the code a little :)

**Comment by illseption** [comment]
Thankyou @soumyaa1804! That fixed it.

**Comment by uyscuti-wiki** [comment]
Hey @illseption, just letting you know I've added the tests for the feature you added in #412. Would be nice if you could take a look and familiarise yourself with writing tests, and of course feel free to ask any questions!

**Comment by illseption** [comment]
Hi @uyscuti-wiki, thank you for your response! I'll be sure to check it out. Could you point me to some resources on writing tests? I've never done it before

**Comment by uyscuti-wiki** [comment]
@illseption sure! Here's Django's [documentation on testing](https://docs.djangoproject.com/en/1.11/topics/testing/), and you can also checkout the tests (in `tests.py` under every app) in this project, which are for the most part straightforward and intuitive.

**Pull request merged**
