### PR TITLE
WIP Upgrade to Django 3.2

### PR DESCRIPTION
**Pull request by jsnshrmn**
## Description
Upgrade to Django 3.2.
The only change needed was an update to our app config to meet the new naming requirements and ensure consistent signal registration in offline environments (eg. tests, management commands)

## Rationale
This is an LTS release, and was a pretty easy update from 3.1

## Phabricator Ticket
https://phabricator.wikimedia.org/T280697

## How Has This Been Tested?
- All unit tests pass
- I pulled a recent backup and clicked through all the apps as well as the admin site. Because of the changes to appConfig, I also submitted and reviewed an application to test signals, which worked fine.

## Screenshots of your changes (if appropriate):
N/A

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

### CODE REVIEW

**Comment by jsnshrmn** [comment]
hmm, this passed locally, but failed in travis. Taking a look.

**Comment by jsnshrmn** [comment]
Interesting. I destroyed my environment and brought it back up, and now tests are failing there too. It looks like the problems are related to the fragment caching, which is going away soon anyway. I'll just let this sit until after we drop those.

**Comment by jsnshrmn** [comment]
It's interesting that we're seeing these failures in travis, as the the thing seems to be humming along happily on my machine, where all tests are also passing:
```
(venv) /app# bin/virtualenv_test.sh ||:
[Mon Apr 26 15:46:03 UTC 2021]
black --target-version py37 --check TWLight
All done! ✨ 🍰 ✨
205 files would be left unchanged.
/app/tests/shunit/twlight_i18n_lint_test.sh
testBadPyNewlines
testGoodPy
testBadPyComments

Ran 3 tests.

OK
Checking for localization issues
No localization issues found
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
.......................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 327 tests in 305.541s

OK
Preserving test database for alias 'default'...
```

**Comment by suecarmol** [comment]
Since we have put T280697 back into the backlog, should we close out this PR?

**Comment by jsnshrmn** [comment]
☝️👌

**Pull request closed without merging**
