### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by jsnshrmn**
https://phabricator.wikimedia.org/T209092

### CODE REVIEW

**Comment by jsnshrmn** [comment]
I've stripped out a bunch of `utf-8` encode/decode. I recall a that during some of our earlier unicode validation @Samwalton9 manually made changes to introduce non-ascii data into our tests. Any recollection of what that was @Samwalton9? I thought I would add something similar here to make sure we don't introduce a regression, since this upgrade touches 100% of our string handling.

**Comment by Samwalton9** [comment]
> I recall a that during some of our earlier unicode validation @Samwalton9 manually made changes to introduce non-ascii data into our tests. Any recollection of what that was @Samwalton9?

I changed some of the Factory Boy fakers to use a different locale, e.g. for editor usernames

**Comment by jsnshrmn** [comment]
Okay, we're now leveraging faker as a gentle unicode fuzzer. Any time we grab text data from faker, it uses a random locale setting. This includes tests and example data

**Comment by jsnshrmn** [comment]
I ran a restore of production data against this, and it's looking good.

**Pull request merged**
