### PR TITLE
Withdraw button will appear only to the status which are PENDING,APPR…

### PR DESCRIPTION
**Pull request by YashAgrawal9265**
[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Withdraw was appearing to all the status except invalid. I make a change in it. Now it will appear to only  PENDING, APPROVED and  UNDER DISCUSSION status.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

## Phabricator Ticket
https://phabricator.wikimedia.org/T268449

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by lalit97** [comment]
Minor suggestion, instead of 
`{% if app.status == app.APPROVED or app.status == app.PENDING or app.status == app.QUESTION %}`
We can write the condition something like 
`{% if app.status in [app.APPROVED, app.PENDING, app.QUESTION] %}`

**Comment by YashAgrawal9265** [comment]
@lalit97 Thank You! for your suggestion but it is showing template syntax error.

**Comment by YashAgrawal9265** [comment]
This syntax might work on JINJA TEMPLATE but not on Django templates.

**Comment by lalit97** [comment]
> @lalit97 Thank You! for your suggestion but it is showing template syntax error.

Oh my bad, I suggested this after reading https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#in-operator but looks like it does not work for lists :(

**Review by jsnshrmn — CHANGES_REQUESTED** [review]
Hi there,

Thanks for your work on this, and apologies for the long wait for review. Since the underlying issue that precipitated this change was that we should not be sent applications to be withdrawn, it warrants adding a test to verify that is so. You could add it right after the existing withdraw test:
https://github.com/WikipediaLibrary/TWLight/blob/cdc42e01085516978d1a7842b96352d5bf94a1ae/TWLight/users/tests.py#L317

**Comment by YashAgrawal9265** [comment]
I have made some changes in the test case.
Please have a look on it.

**Comment by jsnshrmn** [comment]
The we need here is one for an app with the status of `SENT`. We want to test to make sure that those may not be withdrawn.

**Comment by YashAgrawal9265** [comment]
Instead of 4 apps, should I add only 1 app with status as Sent?

**Comment by YashAgrawal9265** [comment]
test for app with status as **sent** cannot be made because when application status is **sent**, in that case withdraw button is not available.

**Comment by jsnshrmn** [comment]
I'm asking for a test that validates that the button is not there in this situation.

**Comment by YashAgrawal9265** [comment]
how I can check that button is available or not in the test? Can you give me some brief idea?

**Comment by jsnshrmn** [comment]
Oh yes, I apologise for omitting an example. The way we've handled this elsewhere in the project is to render the view and then do an `assertNotIn`
Example:
https://github.com/WikipediaLibrary/TWLight/blob/350e5f1ceaa9e4355605aa3e267e4c0dcf6884fc/TWLight/applications/tests.py#L3189

**Comment by YashAgrawal9265** [comment]
I have pushed one commit. Please tell me that what mistake I am making in testcase. It is giving me error.

**Comment by jsnshrmn** [comment]
Two thoughts here:
1) You have replaced the original test case, meaning that you have removed the test that ensures that the withdraw button works. You should be adding a new test rather than replacing the existing one.
1) The issue here is that you've created an application that was sent by no one. If you look at the validation error, you can see that the resulting authorization is failing out for this reason. Normally the authorizer is set to the coordinator who sends the application. You need to set `sent_by` in the application factory to avoid this.

**Comment by YashAgrawal9265** [comment]
I have add one more commit, Please check it.
As you said I have add a different testcase for checking withdraw button for **sent** status.
But now I am getting this error.



Might this error is due to **assertNotIn** . Can you tell me what should I write in **assertNotIn**.

**Comment by jsnshrmn** [comment]
I'm going to encourage you to do some of the legwork on figuring this out. That error is indicating that you are receiving a redirect rather than renderable output. You could try to print some information to your console to find more information about the redirect (status code, in body messages, etc), you could look at the source for the view and the route to see if you can figure out why you are receiving a redirect. If you understand why the redirect is happening, then you can decide if you should follow it, or if you need to do something else in the request setup to prevent it.

**Comment by YashAgrawal9265** [comment]
Can I use logger in the test.py

**Comment by YashAgrawal9265** [comment]
Can I use logger in the test.py?

**Comment by jsnshrmn** [comment]
I usually just throw in a `print()` statement for quick debugging of tests.

**Comment by YashAgrawal9265** [comment]
I found that first I was using **WithdrawApplicationView**  due to which I always get redirect response. So now I have add **ListApplicationView**.
Please check. If I am wrong again, the please correct me.

**Review by jsnshrmn — APPROVED** [review]

**Review by jsnshrmn — APPROVED** [review]
This looks great! Thanks for your work!

**Pull request merged**
