### PR TITLE
Translator comments!

### PR DESCRIPTION
**Pull request by Samwalton9**
The majority of translatable strings now have translator comments. Apologies in advance if I accidentally screwed any formatting.

This file contains the strings I couldn't locate or wasn't sure what to do with, with comments explaining that: [django.po_todo.txt](https://github.com/WikipediaLibrary/TWLight/files/1124532/django.po_todo.txt)

### CODE REVIEW

**Comment by jsnshrmn** [comment]
I went ahead and resolved the code conflicts as they currently stand. Something I noticed:
In some places the comment starts with "Translators:" and in others "Translator:" It should be the plural everywhere.

**Comment by jsnshrmn** [comment]
Sidenote for future PRs:
when you fork a repo, make sure that you create a separate branch for your changes and do the PR based off of that fork.  All you see when resolving merge conflicts is the branch name, not the name of the remote that the branch came from.  Since you are requesting to merge in the master branch of your fork, I was presented with two choices: master or master when picking the winner of each conflict.

**Comment by Samwalton9** [comment]
It did occur to me part way through this process that I might not be being consistent with singular or plural! Is there an easy way to do a quick find and replace for Translator: to Translators:? If not, I'm happy to run through all the files to fix that.

And thanks for pointing that out - apologies for the confusion. I'm not hugely familiar with Github so will bear that in mind for next time!

**Comment by jsnshrmn** [comment]
No worries. I should be able to clean that up.

**Comment by Samwalton9** [comment]
I started fixing this manually, then realised I did it 229 times and stopped 😁

**Comment by jsnshrmn** [comment]
Sidenote: your link to django.po_todo.txt doesn't work for me.  If you have it on hand, send it to me via email or something.

**Pull request merged**
