### PR TITLE
Create one-off email to notify users about Terms of Use update

### PR DESCRIPTION
**Pull request by suecarmol**
[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Created the templates, signal, and task to send a one-off email to notify users about the terms of use update.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)
Our Terms of Use specify that we will update users when we make substantive changes to it. The new library user experience whereby there is just one criterion for accessing the library requires a substantive change, so we need to notify users.

## Phabricator Ticket
[//]: # (Link to the Phabricator ticket)
[T286897](https://phabricator.wikimedia.org/T286897)

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

### CODE REVIEW

**Comment by Samwalton9** [comment]
Will this email send in the user's chosen language (where a translation has been completed)? I notice it doesn't have a `lang` parameter, which some other emails do.

**Review by jsnshrmn — APPROVED** [review]
Looks good! 😎

**Comment by suecarmol** [comment]
> Will this email send in the user's chosen language (where a translation has been completed)? I notice it doesn't have a `lang` parameter, which some other emails do.

I didn't think about that. @jsnshrmn, will the email be sent in a user's preferred language without passing a `lang` parameter?

**Comment by jsnshrmn** [comment]
> Will this email send in the user's chosen language (where a translation has been completed)? I notice it doesn't have a `lang` parameter, which some other emails do.

You are absolutely correct that we need to add that in. We can do a followup pass to catch that, but for now, we at least have the strings merged for translation.

**Pull request merged**
