### PR TITLE
Allow users to hide their applications from Latest Activity (T193776)

### PR DESCRIPTION
**Pull request by Samwalton9**
Couldn't see a good reason to leave the email text on applications because this appeared to be just about the only reason to apply via email.

### CODE REVIEW

**Comment by jsnshrmn** [comment]
Conflicting migrations.

**Comment by jsnshrmn** [comment]
FYI, I did a conflict resolution on ff to exclude hidden OR deleted apps from the timeline.

**Comment by Samwalton9** [comment]
Aha - rebasing is the solution to jasons-work commit sneaking in :D

**Comment by jsnshrmn** [comment]
What's strange is that it really shoulnd't be needed. The diffs between the two forks are correct outside of the PR. I'd call it a github PR implementation quirk.

**Pull request merged**
