### PR TITLE
New home page with Bundle requirements and Library link

### PR DESCRIPTION
**Pull request by Samwalton9**
This replaces the pre-Python3 PR https://github.com/WikipediaLibrary/TWLight/pull/320.

- Removed activity feed from homepage (moved to new View specifically for Latest Activity page)
- Split homepage primarily into two boxes - Bundle and Apply
- Linked to My Collection after login
- Redirect users to homepage by default
- Renamed My Collection to My Library
- Removed pk requirement from My Library (`users/my_library/` instead of `users/my_library/[pk]`)
- Added a redirect from `users/my_collection/[pk]` to `users/my_library`
- Renamed and re-colored some buttons in My Library
- Split some authorization linking logic out to the authorization model
- Linked up homepage Bundle requirements with model fields
- Added a contextual message in the Library Bundle box based on user eligibility status

### CODE REVIEW

**Comment by Samwalton9** [comment]
Note to self: Close this PR and point it at staging instead.

**Comment by Samwalton9** [comment]
Rebased onto staging branch and updated PR to point to that branch.

**Comment by Samwalton9** [comment]
image

Think I'm done here. I ended up including a few additional pieces that were tangentially related to the homepage.

**Comment by Samwalton9** [comment]
Looks like I did accidentally bring across one change from master; the placeholders on the review page. Will rebasing staging fix that?

**Comment by uyscuti-wiki** [comment]
> image
> 
> Think I'm done here. I ended up including a few additional pieces that were tangentially related to the homepage.

Looks great! Can the two boxes be of similar height though?

**Comment by jsnshrmn** [comment]
> 
> 
> Looks like I did accidentally bring across one change from master; the placeholders on the review page. Will rebasing staging fix that?

Your best best would be to rebase this against staging and just pick the last -n commits in the branch, like:  `git rebase -i HEAD~N`

**Comment by Samwalton9** [comment]
I'll fix the above alongside rebasing/merging with https://github.com/WikipediaLibrary/TWLight/pull/401 once that's merged.

**Comment by Samwalton9** [comment]
Attempted to rebase interactively, dropping the additional commits, but getting seemingly random merge conflicts for some reason. Could we update staging from master so that commit exists as expected on staging?

**Comment by jsnshrmn** [comment]
Using your fork
git clone git@github.com:Samwalton9/TWLight.git SamWaltonTWLight
cd SamWaltonTWLight/
git checkout proxy-homepage-redesign


Take a look at the commit log
git log


Newest commits are at the top.
commit a534ce89fcb908e1094b88393ddef9d305d2de37
Author: Sam Walton <samwalton9@gmail.com>
Date:   Tue Feb 25 13:23:14 2020 +0000

    Tidy unused imports

...

commit 7a8d1fcf43b8b4117d5fd4d0a18e4cbbe72c1c24
Author: Sam Walton <samwalton9@gmail.com>
Date:   Fri Nov 22 14:30:28 2019 +0000

    New home page with Bundle requirements and Collection link

commit f2c6f531f60fa04f06f8e9735fcf388defd8c63d
Author: Deployment Bot <deploy@travis-ci.org>
Date:   Wed Feb 12 10:07:28 2020 +0000

    Travis build #2741 translations.

commit b4a37a01ad4d68179b5b4c6aa70117a72a68bb56
Merge: e963af06 60732043
Author: Sam Walton <samwalton9@gmail.com>
Date:   Wed Feb 12 10:01:35 2020 +0000

    Merge pull request #404 from lalit97/T193334

    Add placeholder text to Review filters

commit 60732043aee64fab8e712572d007413a35cbc080
Author: lalit97 <sutharlalit.97@gmail.com>
Date:   Wed Feb 12 14:07:32 2020 +0530

    Add placeholder text to Review filters

    Added placeholder text for username and partner field.

    Bug: T193334

commit 194c31ca6063eed4db86fcd03593b1046effd019
Author: Deployment Bot <deploy@travis-ci.org>
Date:   Tue Feb 11 18:21:14 2020 +0000

    Travis build #2734 translations.


The problem is that this remote branch was based on master when it was slightly ahead of staging. So there are some commits in the middle that don't line up with the revision graph for staging.
Dropping this [merge commit for pull#359](https://github.com/WikipediaLibrary/TWLight/pull/359/commits/b4a37a01ad4d68179b5b4c6aa70117a72a68bb56)

commit b4a37a01ad4d68179b5b4c6aa70117a72a68bb56
Merge: e963af06 60732043
Author: Sam Walton <samwalton9@gmail.com>
Date:   Wed Feb 12 10:01:35 2020 +0000

    Merge pull request #404 from lalit97/T193334

    Add placeholder text to Review filters

and the commits that it merged in should bring the base commit back even with staging.

Do an interactive rebase beginning with the parent commit of the known problem commit (the ^ means commit parent of referenced commit.)
git rebase -i b4a37a01ad4d68179b5b4c6aa70117a72a68bb56^


This will drop you in an editor where you get to pick individual commits. This time, oldest commits are at the top, which is where we need to look.

pick 60732043 Add placeholder text to Review filters
pick f2c6f531 Travis build #2741 translations.
pick 203be878 Capture initial work on determining Editor bundle eligibility upon login.


the default is to pick any commit in the range you specified earlier (this is what a noninteractive rebase does), but we can change pick to drop for any commit we want to get rid of.
If you browse through the [staging commit log](https://github.com/WikipediaLibrary/TWLight/commits/staging?after=194c31ca6063eed4db86fcd03593b1046effd019+34)
you'll see that 60732043 and f2c6f531 are not in the staging commit history, but 203be878 isn't.
change those two lines to drop.

drop 60732043 Add placeholder text to Review filters
drop f2c6f531 Travis build #2741 translations.


and then save the file. The rebase will play.
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
interactive rebase in progress; onto e963af06
Last commands done (53 commands done):
   pick 7a8d1fcf New home page with Bundle requirements and Collection link
   pick b8d89b1d New home page with Bundle requirements and Collection link
Next commands to do (25 remaining commands):
   pick 69c76ca4 Update My Collection to My Library
   pick 4e0e4532 black reformat
You are currently rebasing branch 'proxy-homepage-redesign' on 'e963af06'.

nothing to commit, working tree clean
Could not apply b8d89b1d... New home page with Bundle requirements and Collection link


In this case it had to halt midway through because we have dropped the parent of our base commit. This is fine. When a rebase halts, you can always run git status to see what is going on.
$ git status
interactive rebase in progress; onto e963af06
Last commands done (53 commands done):
   pick 7a8d1fcf New home page with Bundle requirements and Collection link
   pick b8d89b1d New home page with Bundle requirements and Collection link
  (see more in file .git/rebase-merge/done)
Next commands to do (25 remaining commands):
   pick 69c76ca4 Update My Collection to My Library
   pick 4e0e4532 black reformat
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'proxy-homepage-redesign' on 'e963af06'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean

As suggested, just continue
git rebase --continue
Successfully rebased and updated refs/heads/proxy-homepage-redesign.

You're done!

**Comment by Samwalton9** [comment]
Hooray - we're looking good :)

**Comment by Samwalton9** [comment]
I think this is all done and can be reviewed!

**Comment by Samwalton9** [comment]
Rebased successfully, just going to do a pass to resolve our changes more generally.

**Comment by Samwalton9** [comment]
I'm done here, pending a review @jsnshrmn :)

**Pull request merged**
