### PR TITLE
Redevelop tags

### PR DESCRIPTION
**Pull request by suecarmol**
## Description
Redevelop tagging system for subject classification, update tests to pass for the new tagging system, and update partners' tags to reflect the changes.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)
Address inconsistencies in previous tagging system (eg format- vs subject-based tags)

## Phabricator Ticket
[//]: # (Link to the Phabricator ticket)
[T283857](https://phabricator.wikimedia.org/T283857)

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)
Ran the management command manually without any errors (the `new_tags` JSON was validated successfully).

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

### CODE REVIEW

**Review by jsnshrmn — COMMENTED** [review]
This works alright and the code is clean, but I don't love that it would leave the browse partners page in an error state until the management command gets run. I'd recommend wrapping the partners in a guard clause, like
```
        partner_24 = Partner.objects.get(pk=24, company_name="AAAS")
        if partner_24:
                partner_24.new_tags = {
                    "tags": [
                        "life-sciences_tag",
                        "physical-sciences_tag",
                        "health-sciences_tag",
                        "earth-sciences_tag",
                    ]
                }
                partner_24.save()
```
and then calling the command in a migration. That way, it runs on deploy, but is effectively a noop if those partners aren't there.

Having said all that, the code does work as is, and we don't currently have a huge userbase:
if you want to shell in and watch the deploy, I'm sure you could fire the command within a few seconds and have a pretty small window for folks to encounter issues. If that's what you'd like to do, feel free to merge!

**Comment by jsnshrmn** [comment]
Another option would be to drop the management command code directly into a migration

**Comment by suecarmol** [comment]
I have added the migration file to run the command and added a guard clause.

**Comment by jsnshrmn** [comment]
I think the build failure is just down needing to rebase to grab a missing migration and update your migration dependency.

**Comment by suecarmol** [comment]
> I think the build failure is just down needing to rebase to grab a missing migration and update your migration dependency.

Yup, fixed that, CI is running again

**Comment by jsnshrmn** [comment]
Ah, yeah, swapping those `get`s for `filter().first()` will get you a `None` when there is no such object.

**Comment by suecarmol** [comment]
> Ah, yeah, swapping those `get`s for `filter().first()` will get you a `None` when there is no such object.

On it!

**Review by jsnshrmn — APPROVED** [review]
We are go for launch!
🚀🚀🚀

**Pull request merged**
