### PR TITLE
Added option for pre-registration email in applications (T172095)

### PR DESCRIPTION
**Pull request by Samwalton9**
Not sure what I did last time but redid this from scratch and it seems to work correctly. Tests ran OK after modification.

Luckily it looks like this can be merged automatically, do I need to merge master to this branch and then make a fresh PR, or does this work directly?

### CODE REVIEW

**Comment by jsnshrmn** [comment]
Could you squash the migrations in this so that there's just one migration being pulled in?

**Comment by jsnshrmn** [comment]
I was seeing a conflict with master once I had merged in your other changes. I took a stab at resolving the conflict, but I'm not able to build to check at the moment due to a pip mirror outage.

**Comment by jsnshrmn** [comment]
We can see your branch test results right here in the pr if you pull in my travis ci changes.  I've opened a PR on your fork:
https://github.com/Samwalton9/TWLight/pull/2

**Comment by Samwalton9** [comment]
Note to self that this PR also needs to update the send data labels added in https://github.com/WikipediaLibrary/TWLight/pull/71 to include account_email.

**Comment by Samwalton9** [comment]
Should be all done here.

**Pull request merged**
