### PR TITLE
T242196: Updated I Accept to "Submit"

### PR DESCRIPTION
**Pull request by alonea**

### CODE REVIEW

**Comment by Samwalton9** [comment]
Thanks for giving this a go! This is only one of the changes that need to be made for this task, however.

See the changes (and comments) in https://github.com/WikipediaLibrary/TWLight/pull/387.

**Comment by Samwalton9** [comment]
@alonea Just checking that you saw my feedback above, is there anything else I can do to help?

**Comment by alonea** [comment]
Hi @Samwalton9  can you please provide more details on this as i can see some changes are already been handled.

**Comment by uyscuti-wiki** [comment]
Hey @alonea, you can see the changes to make (and not to make) [here](https://github.com/WikipediaLibrary/TWLight/pull/387/files). If that doesn't clarify your doubts, please feel free to ask. Thanks!

**Comment by Samwalton9** [comment]
Closing this PR based on lack of activity.

**Pull request closed without merging**
