### PR TITLE
Stop using external javascript hosting

### PR DESCRIPTION
**Pull request by Shubh1815**
[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Imported javascript libraries directly into the project so we don't need to use CDNs anymore.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

## Phabricator Ticket
[//]: # [https://phabricator.wikimedia.org/T245270](https://phabricator.wikimedia.org/T245270)

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
- Can this change be tested manually? How? Yes
- I have tested it manually by checking for errors in the developers tools also by testing whether things like dropdowns and tabs are working with this imported library, and its working and there aren't any new errors due to this imported libraries.

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by jsnshrmn — COMMENTED** [review]
This is a pretty straightforward change, so while I understand the desire to to just skip to the code, could you please fill out the details of how you tested this in the PR template? Did you just update the code changes and push it without checking?  Did you stand up the local environment and spot check that the libraries loaded? Please let us know. Thanks for your work on this!

**Comment by Shubh1815** [comment]
I have updated the PR template, let me know if I need to change anything.

**Review by jsnshrmn — CHANGES_REQUESTED** [review]
Apologies in the delay in re-reviewing. Thank you for updating your PR to give me more information. Looking through the codebase, there are still several references to externally hosted javascript. I recommend searching the codebase for `script src="http` or for `tools-static` to help ensure that you get them all.

**Comment by Shubh1815** [comment]
Hey @jsnshrmn, I have made the necessary changes so could you please review them.

**Review by jsnshrmn — APPROVED** [review]
Apologies for the delay. This looks great! Thanks!

**Pull request merged**
